# Synced with https://github.com/coreos/etcd-operator/blob/master/pkg/util/k8sutil/crd.go
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
  labels:
    app: etcd-operator.name
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  group: etcd.database.coreos.com
  scope: Namespaced
  version: v1beta2
  names:
    kind: EtcdCluster
    listKind: EtcdClusterList
    singular: etcdcluster
    plural: etcdclusters
    shortNames:
    - etcd
  versions:
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
